CREATE TABLE books (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    price DOUBLE,
    category VARCHAR(255),
    language VARCHAR(255),
    pages INTEGER,
    publication_year INTEGER,
    description VARCHAR(1000),
    available BOOLEAN
);